import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    innerContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        padding: 20,
        borderRadius: 10,
        width: '80%',
    },
    welcomeText: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#333',
        marginBottom: 20,
    },
    formContainer: {
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
        marginVertical: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 20,
        color: '#333',
    },
    input: {
        height: 50,
        borderColor: '#ddd',
        borderWidth: 1,
        borderRadius: 10,
        marginBottom: 16,
        paddingHorizontal: 12,
        fontSize: 16,
        backgroundColor: '#f9f9f9',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    button: {
        backgroundColor: '#4CAF50',
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 3,
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '500',
    },
    resultsContainer: {
        marginTop: 16,
        backgroundColor: '#fff',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        padding: 10,
    },
    resultsText: {
        fontWeight: 'bold',
        fontSize: 20,
        marginBottom: 10,
        textAlign: 'center',
    },
    headerRow: {
        flexDirection: 'row',
        backgroundColor: '#4CAF50',
        borderTopLeftRadius: 8,
        borderTopRightRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 8,
        marginBottom: 6,
    },
    lineHeader: {
        flex: 1,
        color: '#fff',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 16,
        paddingHorizontal: 4,
    },
    latLonHeader: {
        flex: 2,
        color: '#fff',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 16,
        paddingHorizontal: 8, // Increased padding for better spacing
    },
    timestampHeader: {
        flex: 2,
        color: '#fff',
        fontWeight: 'bold',
        textAlign: 'center',
        fontSize: 16,
        paddingHorizontal: 8,
    },
    row: {
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 8,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        marginVertical: 2,
        borderRadius: 8,
        elevation: 1,
    },
    lineCell: {
        flex: 1,
        textAlign: 'center',
        color: '#333',
        fontSize: 14,
        paddingHorizontal: 4,
    },
    latLonCell: {
        flex: 2,
        textAlign: 'center',
        color: '#333',
        fontSize: 14,
        paddingHorizontal: 8, // Increased padding for better spacing
    },
    timestampCell: {
        flex: 2,
        textAlign: 'center',
        color: '#333',
        fontSize: 14,
        paddingHorizontal: 8,
    },
});


export default styles;